export const MODAL_MODES = { EDIT: 'Edit', ADD: 'Add' }

export const DEVICE_TYPES = {MAC: 'MAC', WINDOWS: 'WINDOWS', LINUX: 'LINUX', ANY: 'ALL' }

export const SORT_OPTIONS = {
    CAP_ASCENDING: 'CAP,ASC',
    CAP_DESCENDING: 'CAP,DESC',
    NAME_ASCENDING: 'NAME,ASC',
    NAME_DESCENDING: 'NAME,DESC'
};